# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0004_selections'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
