# Generated by Django 4.2.7 on 2023-11-29 18:03

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of color')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Rəng')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Condition',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Modes')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Model')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turbo.marka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modeller',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('city', models.CharField(choices=[('Baki', 'Baki'), ('Gence', 'Gence'), ('Sumqayit', 'Sumqayit'), ('Lenkeran', 'Lenkeran')], max_length=255)),
                ('release_year', models.CharField(max_length=255, verbose_name='Buraxilis ili')),
                ('ban_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Cip', 'Cip'), ('Offroad', 'Offroad'), ('Crossover', 'Crossover')], max_length=255)),
                ('engine', models.CharField(max_length=255, verbose_name='Muherrik')),
                ('km', models.CharField(max_length=255, verbose_name='Probeq')),
                ('gear_box', models.CharField(choices=[('Mexaniki', 'Mexaniki'), ('Avtomat', 'Avtomat'), ('Variator', 'Variator'), ('Robotlasdirilmis', 'Robotlasdirilmis')], max_length=255)),
                ('oturucu', models.CharField(choices=[('on', 'on'), ('arxa', 'arxa'), ('tam', 'tam')], max_length=255)),
                ('is_new', models.CharField(choices=[('Yeni', 'Yeni'), ('Surulmus', 'Surulmus')], max_length=255)),
                ('count_of_seats', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('store_country', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('user_view_count', models.IntegerField()),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turbo.color')),
                ('condition', models.ManyToManyField(blank=True, null=True, to='turbo.condition')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turbo.marka')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turbo.model')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='turbo.tags')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
